# Notebook for some fundamentals of Python :) 

## Random numbers 

In [ ]:
import random
#random number in [0,1)
print(random.random())
#random real number in [2,6]
print(random.uniform(2,6))
#random integer number in [2,6]
print(random.randint(2,6))

In [ ]:
#one coin flip
print(random.randint(0,1))
#coin flip n times
#fair coin 
n=100
l = random.choices(range(0,2), k=n)
#unfair coin 
#l = random.choices(range(0,2), [0.2,0.8], k=n)
print(sum(l)/n)

In [ ]:
#die rolling one time
print(random.randint(1,6))

#die rolling n times
n=10000
#fair die
l = random.choices(range(1,7), k=n)
#unfair die
#l = random.choices(range(1,7),weights=[0.05,0.05,0.4,0.4,0.05,0.05], k=n)
#print(l)
n_3 = 0
for v in l:
    if(v==3):
        n_3 += 1 
print(n_3/n*100) #it will be around 16%
#using list comprehensions
n_3 = sum([v/3 for v in l if(v==3)])
print(n_3/n*100) #it will be around 16%


## Arrays in numpy

In [8]:
import numpy as np
#create vector given values in it
a = np.array([1, 2, 3])
print(a)
print(a[1])
print(a.shape)
print(np.matrix(a))
print("-----")
#create matrix of 0's of given size
b = np.ones((3,1))
print(b)
print(b.shape)
b = b*3
print(b)
print("-----")
#create matrix of 1's of given size
c = np.ones((2,3))
print(c)
print("-----")
#create identity matrix of size n
d = np.eye(4)
print(d)
print("-----")
#random number in [0,1)
print(np.random.random())
print("-----")
#random integer number in [1,6]
print(np.random.randint(1,6))
print("-----")
#create random matrix (values in [0,9]) of given size 2x4
e = np.random.randint(0,9,(2,4))
print(e)
print(e[0][1])
#create random list (values in [0,9]) using numpy
l = np.random.randint(0,9,(1,4)).tolist()[0]
print(l)

[1 2 3]
2
(3,)
[[1 2 3]]
-----
[[1.]
 [1.]
 [1.]]
(3, 1)
[[3.]
 [3.]
 [3.]]
-----
[[1. 1. 1.]
 [1. 1. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-----
0.9808432828620933
-----
1
-----
[[5 8 5 7]
 [8 5 6 3]]
8
[6, 8, 5, 3]


## Arrays indexing in numpy

In [ ]:
print(e[:1,:])
print(e[:1])

In [ ]:
print(e[:,0:4])

In [ ]:
print(e[:,1:1])

In [ ]:
print(e[:,1:3])

In [ ]:
print(e[:,1:-1])

In [ ]:
print(e[0,1:])

In [ ]:
print(e[0,0:])

## Some sorting algorithm using numpy arrays

In [ ]:
#selection sort 

def selection_sort(x):
    for i in range(len(x)):
        swap = i + np.argmin(x[i:])
        #with temporary variable "temp"
        #temp = x[i]
        #x[i] = x[swap]
        #x[swap] = temp
        #without temporary variable "temp", but using tuples (super Python's skills :)
        (x[i], x[swap]) = (x[swap], x[i])
    return x

x = np.array([2, 1, 4, 3, 5])
print(x)
print(selection_sort(x))

In [ ]:
#bogo sort :)) 
#homework: try to implement this function using another function that check if x is sorted (without np.any)

def bogosort(x):
    while np.any(x[:-1] > x[1:]): 
        np.random.shuffle(x)
    return x

x = np.array([2, 1, 4, 3, 5])
#print(x[:-1])
#print(x[1:])
#print(x[:-1] > x[1:])
print(x)
print(bogosort(x))

## Reading from file

In [ ]:
file_name = "data/pima-indians-diabetes.csv"
infile = open(file_name,'r')
n_lines = 0
for line in infile:
    if n_lines <=4:
        print(line)
    n_lines += 1
print("Number of lines in file:", n_lines)
#print(type(line))
infile.close()

In [ ]:
file_name = "data/pima-indians-diabetes.csv"
infile = open(file_name,'r')
n_lines = 0
for line in infile:
    if n_lines <=4:
        print("Line:\n"+line)
        v = line.split(',')
        print("List: "+str(v))
        print("Elements in list:")
        for i in range(len(v)):
            print(v[i].strip())
        print("\n")
    n_lines += 1
infile.close()

In [ ]:
import csv

filename = "data/pima-indians-diabetes.csv"

lines = csv.reader(open(filename, 'r'))

for line in lines:
    print(line)

## Writing to file

In [ ]:
infile_name = "data/pima-indians-diabetes.csv"
infile = open(file_name,'r')
line_c = 0
outfile_name = "prova.txt"
outfile = open(outfile_name,'w')
for line in infile:
    if line_c <=4:
        outfile.write("Line:\n"+line+"\n")
        v = line.split(',')
        outfile.write("List: "+str(v)+"\n")
        outfile.write("Elements in list:\n")
        for i in range(len(v)):
            outfile.write(v[i].strip()+"\n")
        outfile.write("\n")
    line_c += 1
infile.close()
outfile.close()